name: unit  tests
on:
  push:
    branches:
      - "master"
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.8.0-dev.1772+5ebcd8cca
      - run: zig build test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.8.0-dev.1772+5ebcd8cca
      - run: zig fmt --check src/*.zig
